### ISSUE TITLE
Better Way to reference WASM Service?

### ISSUE THREAD

**Issue by aherrick** [hakenr/BlazorGrpcWebCodeFirst#1]
Hi! This is a cool project.

Wondering if there is a better way to reference the actual Client Service than having to include all this code in the Index file itself.

```
		var handler = new Grpc.Net.Client.Web.GrpcWebHandler(Grpc.Net.Client.Web.GrpcWebMode.GrpcWeb, new HttpClientHandler());
		using (var channel = Grpc.Net.Client.GrpcChannel.ForAddress("https://localhost:44383/", new Grpc.Net.Client.GrpcChannelOptions() { HttpClient = new HttpClient(handler) }))
		{
			var testFacade = channel.CreateGrpcService<IMyService>();
			this.result = await testFacade.DoSomething(request);
		}
```

Is something like this Builder Pattern possible to inject the service?

https://docs.microsoft.com/en-us/aspnet/core/grpc/browser?view=aspnetcore-5.0#additional-resources

**Comment by hakenr** [comment]
@aherrick, I will try to get to that tomorrow, it should be able to register the interfaces into ServiceCollection using factory methods and use regular dependency injection where needed.

**Comment by aherrick** [comment]
Awesome! Looking forward to trying it out
